const express = require('express');
const controller = require('../controllers/accountingController');
const settlement = require('../controllers/settlementController');
const payroll = require('../controllers/payrollController');
const payrollVoucher = require('../controllers/payrollVoucherController');
const paymentVoucher = require('../controllers/paymentVoucherController');
const reportController = require('../controllers/reportController');
const { verifyToken, requireRole, requirePermission, requireAnyPermission } = require('../middlewares/authMiddleware');
const accountantPayroll = [requireRole('Kế toán'), requirePermission('UC33')];

const router = express.Router();
router.use(verifyToken);
router.get('/receipt-files', requirePermission('UC27'), controller.listReceiptFiles);
router.get('/receipt-files/:id', requirePermission('UC27'), controller.getReceiptFile);
router.get('/purchase-order-files', requirePermission('UC27'), controller.listPurchaseOrderFiles);
router.get('/purchase-order-files/:id', requirePermission('UC27'), controller.getPurchaseOrderFile);
router.get('/purchase-invoices', requirePermission('UC27'), controller.listInvoices);
router.get('/purchase-invoices/:id/reconciliation-preview', requirePermission('UC27'), controller.previewReconciliation);
router.get('/purchase-invoices/:id', requirePermission('UC27'), controller.getInvoiceDetail);
router.post('/purchase-invoices', requirePermission('UC27'), controller.createInvoice);
router.post('/purchase-invoices/:id/reconcile', requirePermission('UC27'), controller.reconcileInvoice);
router.get('/payables', requirePermission('UC28'), paymentVoucher.listPayables);
router.get('/payables/:id', requirePermission('UC28'), paymentVoucher.getPayable);
router.post('/payables/:id/payment-voucher', requirePermission('UC28'), paymentVoucher.createVoucher);
router.post('/payment-vouchers/:id/resubmit', requirePermission('UC28'), paymentVoucher.resubmitVoucher);
router.post('/payment-vouchers/:id/pay', requirePermission('UC28'), paymentVoucher.payVoucher);
router.get('/shift-settlements', requirePermission('UC29'), settlement.listShifts);
router.get('/shift-settlements/:id', requirePermission('UC29'), settlement.getShift);
router.post('/shift-settlements/:id/receipt', requirePermission('UC29'), settlement.createReceipt);
router.post('/shift-receipts/:id/confirm', requirePermission('UC29'), settlement.confirmReceipt);
router.get('/reports/financial-summary', requirePermission('UC29'), reportController.getFinancialReport);
router.get('/activity-log', requireRole('Kế toán'), requireAnyPermission(['UC27', 'UC28', 'UC29', 'UC33']), payrollVoucher.getAccountantActivity);
router.get('/payroll-payouts', accountantPayroll, payrollVoucher.getPayoutHistory);
router.get('/payroll/:month', accountantPayroll, payroll.get);
router.post('/payroll/:month/build', accountantPayroll, payroll.build);
router.post('/payroll/:month/lock', accountantPayroll, payroll.lock);
router.post('/payroll/:month/payment-vouchers', accountantPayroll, payrollVoucher.createVouchers);
router.get('/payroll/:month/:employee/details', accountantPayroll, payroll.getDetails);
router.post('/payroll/:month/:employee/pay', accountantPayroll, payroll.pay);
router.post('/payroll-vouchers/:id/resubmit', accountantPayroll, payrollVoucher.resubmitVoucher);
router.post('/payroll-vouchers/:id/pay', accountantPayroll, payrollVoucher.payVoucher);

module.exports = router;
