const express = require('express');
const adminController = require('../controllers/adminController');
const catalogController = require('../controllers/catalogController');
const orderController = require('../controllers/purchaseOrderController');
const workforceController = require('../controllers/workforceController');
const returnsController = require('../controllers/returnsController');
const inventoryCountController = require('../controllers/inventoryCountController');
const stockIssueController = require('../controllers/stockIssueController');
const paymentVoucherController = require('../controllers/paymentVoucherController');
const payrollVoucherController = require('../controllers/payrollVoucherController');
const holidayController = require('../controllers/holidayController');
const reportController = require('../controllers/reportController');
const backupController = require('../controllers/backupController');
const { verifyToken, requireRole, requirePermission } = require('../middlewares/authMiddleware');
const { uploadProductImage } = require('../middlewares/productImageUpload');

const router = express.Router();

router.use(verifyToken);
router.use(requireRole('Quản lý'));
router.get('/dashboard', adminController.getDashboard);
router.get('/approvals/queues', requirePermission('UC05'), adminController.getApprovalQueues);
router.get('/finance/payables', requirePermission('UC10'), adminController.getPayablesOverview);
router.get('/finance/payables/:id', requirePermission('UC10'), adminController.getPayableDetail);
router.get('/finance/sales-shifts', requirePermission('UC10'), adminController.getSalesShifts);
router.get('/reports/financial-summary', requirePermission('UC10'), reportController.getFinancialReport);
router.get('/reports/store-operations', requirePermission('UC10'), reportController.getStoreOperationsReport);
router.get('/reports/store-profit-loss', requirePermission('UC10'), reportController.getStoreProfitLossReport);
router.post('/reports/store-profit-loss/plan', requirePermission('UC10'), reportController.postStoreProfitLossPlan);
router.get('/catalog/categories', requirePermission('UC04'), catalogController.getCategories);
router.post('/catalog/categories', requirePermission('UC04'), catalogController.createCategory);
router.put('/catalog/categories/:id', requirePermission('UC04'), catalogController.updateCategory);
router.patch('/catalog/categories/:id/status', requirePermission('UC04'), catalogController.setCategoryStatus);
router.get('/catalog/products', requirePermission('UC04'), catalogController.getProducts);
router.post('/catalog/products', requirePermission('UC04'), uploadProductImage, catalogController.createProduct);
router.put('/catalog/products/:id', requirePermission('UC04'), uploadProductImage, catalogController.updateProduct);
router.patch('/catalog/products/:id/status', requirePermission('UC04'), catalogController.setProductStatus);
router.get('/catalog/promotions', requirePermission('UC04'), catalogController.getPromotions);
router.post('/catalog/promotions', requirePermission('UC04'), catalogController.savePromotion);
router.put('/catalog/promotions/:id', requirePermission('UC04'), catalogController.savePromotion);
router.patch('/catalog/promotions/:id/status', requirePermission('UC04'), catalogController.setPromotionStatus);
router.get('/approvals/purchase-orders', requirePermission('UC05'), orderController.list);
router.get('/approvals/purchase-orders/:id', requirePermission('UC05'), orderController.getDetail);
router.post('/approvals/purchase-orders/:id/approve', requirePermission('UC05'), orderController.approve);
router.post('/approvals/purchase-orders/:id/request-changes', requirePermission('UC05'), orderController.requestChanges);
router.post('/approvals/purchase-orders/:id/reject', requirePermission('UC05'), orderController.reject);
router.get('/approvals/returns/:id', requirePermission('UC08'), returnsController.getReturn);
router.post('/approvals/returns/:id/approve', requirePermission('UC08'), returnsController.decideReturn(true));
router.post('/approvals/returns/:id/reject', requirePermission('UC08'), returnsController.decideReturn(false));
router.get('/approvals/inventory-counts/:id', requirePermission('UC07'), inventoryCountController.getApprovalCountDetail);
router.post('/approvals/inventory-counts/:id/approve', requirePermission('UC07'), inventoryCountController.approveCount);
router.post('/approvals/inventory-counts/:id/reject', requirePermission('UC07'), inventoryCountController.rejectCount);
router.get('/approvals/stock-issues/:id', requirePermission('UC06'), stockIssueController.getApprovalIssueDetail);
router.post('/approvals/stock-issues/:id/approve', requirePermission('UC06'), stockIssueController.approveIssue);
router.post('/approvals/stock-issues/:id/reject', requirePermission('UC06'), stockIssueController.rejectIssue);
router.get('/approvals/payment-vouchers/:id', requirePermission('UC09'), paymentVoucherController.getApprovalDetail);
router.post('/approvals/payment-vouchers/:id/approve', requirePermission('UC09'), paymentVoucherController.approveVoucher);
router.post('/approvals/payment-vouchers/:id/reject', requirePermission('UC09'), paymentVoucherController.rejectVoucher);
router.get('/approvals/payroll-board', requirePermission('UC09'), payrollVoucherController.listBoard);
router.get('/approvals/payroll-vouchers', requirePermission('UC09'), payrollVoucherController.listPending);
router.post('/approvals/payroll-vouchers/approve-all', requirePermission('UC09'), payrollVoucherController.approveAll);
router.post('/approvals/payroll-fund/:month/handover', requirePermission('UC09'), payrollVoucherController.handOverFund);
router.get('/approvals/payroll-vouchers/:id', requirePermission('UC09'), payrollVoucherController.getApprovalDetail);
router.post('/approvals/payroll-vouchers/:id/approve', requirePermission('UC09'), payrollVoucherController.approveVoucher);
router.post('/approvals/payroll-vouchers/:id/reject', requirePermission('UC09'), payrollVoucherController.rejectVoucher);
router.get('/workforce/holidays/:year', requirePermission('UC30'), holidayController.getHolidays);
router.put('/workforce/holidays/:year', requirePermission('UC30'), holidayController.saveHolidays);
router.put('/workforce/pay-rates', requirePermission('UC30'), holidayController.saveRates);
router.get('/workforce/setup', requirePermission('UC30'), workforceController.getSetup);
router.get('/workforce/schedules', requirePermission('UC30'), workforceController.getSchedules);
router.post('/workforce/schedules/auto', requirePermission('UC30'), workforceController.autoSchedule);
router.put('/workforce/schedules', requirePermission('UC30'), workforceController.saveSchedule);
router.delete('/workforce/schedules/:id', requirePermission('UC30'), workforceController.deleteSchedule);
router.post('/workforce/schedules/publish', requirePermission('UC30'), workforceController.publishSchedules);
router.get('/workforce/attendance', requirePermission('UC32'), workforceController.getAttendance);
router.post('/workforce/attendance/:id/approve', requirePermission('UC32'), workforceController.approveAttendance);
router.get('/workforce/payroll-preview', requirePermission('UC32'), workforceController.getPayrollPreview);

router.post('/backup', backupController.createBackup);
router.get('/backups', backupController.listBackups);
router.get('/backups/:fileName', backupController.downloadBackup);
router.get('/security-logs', backupController.getSecurityLogs);

module.exports = router;
