(() => {
  const previous = window.FLY_ROLE_PAGES;
  const templates = {
    'warehouse-receiving': '<section class="warehouse-page"><div class="overview-loading">Đang tải hàng chờ nhận...</div></section>',
    'warehouse-receipts': '<section class="warehouse-page"><div class="overview-loading">Đang tải Phiếu nhập kho...</div></section>'
  };
  const esc = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
  const money = value => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(Number(value || 0));
  const fmtDate = value => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(value)) : '—';
  const statusClass = status => ({ 'Nháp': 'draft', 'Đã xác nhận': 'ok', 'Nhà cung cấp xác nhận': 'ok', 'Đã gửi Nhà cung cấp': 'processing', 'Đang giao': 'processing', 'Đã đến kho': 'sent', 'Đang kiểm nhận': 'processing', 'Đã kiểm nhận': 'ok', 'Giao một phần': 'returned' }[status] || 'draft');
  const api = async (context, path, options = {}) => {
    const response = await fetch(`${context.apiBase}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${context.token}`, ...(options.headers || {}) } });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.message || 'Không thể xử lý yêu cầu.');
    return data;
  };
  const heading = (kicker, title, subtitle, action = '') => `<header class="warehouse-heading"><div><p class="warehouse-kicker">${esc(kicker)}</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action}</header>`;

  const receiptDetail = async (context, id, onDone = async () => {}) => {
    try {
      const data = await api(context, `/warehouse/receipts/${id}`);
      const receipt = data.receipt;
      const overlay = document.createElement('div'); overlay.className = 'warehouse-modal-backdrop';
      const rows = data.lines.map(line => `<tr><td><strong>${esc(line.TenSP)}</strong><small>${esc(line.MaSP)} · ${esc(line.DonViTinh)}</small></td><td class="num">${line.SoLuongGiao}</td><td class="num"><strong>${line.SoLuongChapNhan}</strong></td><td class="num">${line.SoLuongTuChoi}</td><td class="num">${money(line.DonGiaNhap)}</td><td>${esc(line.TinhTrangHang || '—')}<small>${esc(line.LyDoTuChoi || '')}</small></td><td>${esc(line.SoLo || '—')}<small>${line.HanSD ? `HSD ${fmtDate(line.HanSD).split(' ')[0]}` : ''}</small></td></tr>`).join('');
      const confirmAction = receipt.TrangThai === 'Nháp' ? '<button class="warehouse-primary confirm-receipt">Xác nhận nhập kho</button>' : '';
      overlay.innerHTML = `<div class="warehouse-modal"><div class="warehouse-modal-heading"><div><p class="warehouse-kicker">PHIẾU KIỂM NHẬN HÀNG</p><h2>${esc(receipt.MaPN)}</h2></div><button class="warehouse-icon-button close">×</button></div><div class="warehouse-modal-body"><div class="warehouse-detail-grid"><div><span>ĐƠN MUA</span><strong>${esc(receipt.MaPO)}</strong></div><div><span>NHÀ CUNG CẤP</span><strong>${esc(receipt.TenNCC)}</strong></div><div><span>KHO NHẬN</span><strong>${esc(receipt.TenKho)}</strong></div><div><span>NGƯỜI KIỂM NHẬN</span><strong>${esc(receipt.NguoiKiemNhan)}</strong></div><div><span>TRẠNG THÁI</span><strong><span class="status-pill ${statusClass(receipt.TrangThai)}">${esc(receipt.TrangThai)}</span></strong></div><div><span>GIÁ TRỊ CHẤP NHẬN</span><strong>${money(receipt.TongTien)}</strong></div></div><p class="warehouse-modal-note"><strong>Nguyên tắc:</strong> chỉ số lượng chấp nhận được cộng vào tồn kho; số lượng từ chối vẫn là phần Nhà cung cấp chưa giao đủ.</p><div class="warehouse-table-wrap warehouse-form-lines"><table class="warehouse-table"><thead><tr><th>MẶT HÀNG</th><th>GIAO</th><th>CHẤP NHẬN</th><th>TỪ CHỐI</th><th>ĐƠN GIÁ</th><th>TÌNH TRẠNG</th><th>LÔ / HSD</th></tr></thead><tbody>${rows}</tbody></table></div></div><div class="warehouse-modal-actions"><button class="warehouse-secondary close">Đóng</button><button class="warehouse-secondary print-receipt"><svg><use href="#i-report"/></svg>Xem bản in</button>${confirmAction}</div></div>`;
      document.body.appendChild(overlay);
      const close = () => overlay.remove(); overlay.querySelectorAll('.close').forEach(button => button.addEventListener('click', close)); overlay.addEventListener('click', event => { if (event.target === overlay) close(); });
      overlay.querySelector('.print-receipt').addEventListener('click', () => window.FLY_PRINT.show({
        title: receipt.TrangThai === 'Đã xác nhận' ? 'PHIẾU NHẬP KHO' : 'BIÊN BẢN KIỂM NHẬN HÀNG',
        number: receipt.MaPN, documentDate: receipt.NgayXacNhan || receipt.NgayNhap, status: receipt.TrangThai,
        fields: [
          { label: 'Đơn mua', value: receipt.MaPO }, { label: 'Nhà cung cấp', value: receipt.TenNCC },
          { label: 'Kho nhập', value: receipt.TenKho }, { label: 'Người kiểm nhận', value: receipt.NguoiKiemNhan }
        ],
        columns: [
          { label: 'Mã hàng', key: 'MaSP' }, { label: 'Tên mặt hàng', key: 'TenSP' }, { label: 'ĐVT', key: 'DonViTinh' },
          { label: 'SL giao', key: 'SoLuongGiao', align: 'right' }, { label: 'SL nhập', key: 'SoLuongChapNhan', align: 'right' },
          { label: 'Từ chối', key: 'SoLuongTuChoi', align: 'right' }, { label: 'Đơn giá', key: 'DonGiaNhap', format: 'money', align: 'right' },
          { label: 'Số lô', key: 'SoLo' }, { label: 'Hạn dùng', key: 'HanSD', format: 'date' }
        ], rows: data.lines, totals: [
          { label: 'Tổng số lượng nhập', value: data.lines.reduce((sum, line) => sum + Number(line.SoLuongChapNhan || 0), 0) },
          { label: 'Tổng giá trị nhập', value: receipt.TongTien, format: 'money' }
        ], note: receipt.GhiChu || 'Số lượng từ chối không được ghi tăng tồn kho.',
        signatures: ['Đại diện Nhà cung cấp', 'Thủ kho kiểm nhận', 'Kế toán']
      }));
      overlay.querySelector('.confirm-receipt')?.addEventListener('click', async () => {
        const button = overlay.querySelector('.confirm-receipt'); button.disabled = true;
        try { const result = await api(context, `/warehouse/receipts/${id}/confirm`, { method: 'POST' }); context.showToast(result.message, 'success'); close(); await onDone(); }
        catch (error) { button.disabled = false; context.showToast(error.message, 'error'); }
      });
    } catch (error) { context.showToast(error.message, 'error'); }
  };

  const receivingModal = async (context, shipmentId, onDone) => {
    try {
      const data = await api(context, `/warehouse/receiving/shipments/${shipmentId}`);
      const overlay = document.createElement('div'); overlay.className = 'warehouse-modal-backdrop';
      const rows = data.lines.map(line => `<div class="warehouse-receipt-line" data-product="${esc(line.MaSP)}"><div class="receipt-product"><strong>${esc(line.TenSP)}</strong><small>${esc(line.MaSP)} · Còn thiếu ${line.SLConThieu} ${esc(line.DonViTinh)}</small></div><input class="delivered" aria-label="Số lượng giao" type="number" min="0" max="${line.SLConThieu}" value="${line.SLConThieu}"><input class="accepted" aria-label="Số lượng chấp nhận" type="number" min="0" max="${line.SLConThieu}" value="${line.SLConThieu}"><input class="rejected" aria-label="Số lượng từ chối" type="number" min="0" max="${line.SLConThieu}" value="0"><input class="receipt-price" aria-label="Đơn giá nhập" type="number" min="0" step="100" value="${Number(line.DonGia)}"><input class="lot" aria-label="Số lô" maxlength="50" placeholder="Số lô">${window.FLY_VI_DATE.dateField(`expiry-${line.MaSP}`, '', 'expiry', true)}<input class="location" aria-label="Vị trí kho" maxlength="100" placeholder="Kệ / vị trí"><input class="reject-reason" aria-label="Tình trạng hoặc lý do từ chối" maxlength="300" placeholder="Tình trạng hàng / lý do từ chối"></div>`).join('');
      overlay.innerHTML = `<div class="warehouse-modal receipt-modal"><div class="warehouse-modal-heading"><div><p class="warehouse-kicker">NHẬN VÀ KIỂM TRA HÀNG</p><h2>${esc(data.order.MaPO)} · ${esc(data.order.TenNCC)}</h2></div><button class="warehouse-icon-button close">×</button></div><div class="warehouse-modal-body"><div class="shipment-arrival-summary"><div><span>PHIẾU GIAO</span><strong>${esc(data.order.SoPhieuGiao)}</strong><small>${esc(data.order.MaTBGH)}</small></div><div><span>XE GIAO HÀNG</span><strong>${esc(data.order.BienSoXe || 'Chưa cung cấp')}</strong><small>${esc(data.order.TenTaiXe || '')}${data.order.SDTTaiXe ? ` · ${esc(data.order.SDTTaiXe)}` : ''}</small></div><div><span>XE ĐẾN KHO LÚC</span><strong>${fmtDate(data.order.NgayDen)}</strong><small>${data.order.SoKien === null || data.order.SoKien === undefined ? 'Chưa ghi số kiện' : `${data.order.SoKien} kiện dự kiến`}</small></div></div><div class="warehouse-form-grid"><div class="warehouse-field"><label>Kho nhận hàng *</label><select id="receiptWarehouse">${data.warehouses.map(item => `<option value="${esc(item.MaKho)}">${esc(item.TenKho)} · ${esc(item.DiaChi || 'Hà Nội')}</option>`).join('')}</select></div><div class="warehouse-field"><label>Ghi chú kiểm nhận</label><input id="receiptNote" maxlength="500" placeholder="Tình trạng niêm phong, chứng từ kèm theo..."></div></div><div class="receipt-rule"><svg><use href="#i-warning"></use></svg><span>Kiểm đếm thực tế từng mặt hàng. Số giao = số chấp nhận + số từ chối. Lưu Phiếu chưa làm tăng tồn kho.</span></div><div class="warehouse-receipt-lines"><div class="warehouse-receipt-line heading"><span>MẶT HÀNG</span><span>GIAO</span><span>ĐẠT</span><span>TỪ CHỐI</span><span>ĐƠN GIÁ</span><span>SỐ LÔ</span><span>HẠN DÙNG</span><span>VỊ TRÍ</span><span>TÌNH TRẠNG</span></div>${rows}</div></div><div class="warehouse-modal-actions"><button class="warehouse-secondary close">Hủy</button><button class="warehouse-primary save-receipt">Lưu Phiếu kiểm nhận</button></div></div>`;
      document.body.appendChild(overlay);
      const close = () => overlay.remove(); overlay.querySelectorAll('.close').forEach(button => button.addEventListener('click', close)); overlay.addEventListener('click', event => { if (event.target === overlay) close(); });
      overlay.querySelectorAll('.warehouse-receipt-line[data-product]').forEach(row => {
        const delivered = row.querySelector('.delivered'); const accepted = row.querySelector('.accepted'); const rejected = row.querySelector('.rejected');
        const syncAccepted = () => { rejected.value = Math.max(0, Number(delivered.value || 0) - Number(accepted.value || 0)); };
        const syncRejected = () => { accepted.value = Math.max(0, Number(delivered.value || 0) - Number(rejected.value || 0)); };
        delivered.addEventListener('input', () => { accepted.max = delivered.value; rejected.max = delivered.value; if (Number(accepted.value) > Number(delivered.value)) accepted.value = delivered.value; syncAccepted(); });
        accepted.addEventListener('input', syncAccepted); rejected.addEventListener('input', syncRejected);
      });
      overlay.querySelector('.save-receipt').addEventListener('click', async () => {
        const lineNodes = Array.from(overlay.querySelectorAll('.warehouse-receipt-line[data-product]'));
        const deliveredNodes = lineNodes.filter(row => Number(row.querySelector('.delivered').value || 0) > 0);
        if (!deliveredNodes.length) return context.showToast('Chuyến xe phải có ít nhất một mặt hàng được giao thực tế.', 'error');
        const lines = deliveredNodes.map(row => { const rejected = Number(row.querySelector('.rejected').value || 0); const note = row.querySelector('.reject-reason').value.trim(); return { MaSP: row.dataset.product, SoLuongGiao: Number(row.querySelector('.delivered').value), SoLuongChapNhan: Number(row.querySelector('.accepted').value), SoLuongTuChoi: rejected, DonGiaNhap: Number(row.querySelector('.receipt-price').value), SoLo: row.querySelector('.lot').value, HanSD: row.querySelector('.expiry').value || null, ViTriKho: row.querySelector('.location').value, TinhTrangHang: rejected ? 'Có hàng không đạt' : (note || 'Đạt yêu cầu'), LyDoTuChoi: rejected ? note : null }; });
        if (lines.some((line, index) => line.SoLuongTuChoi > 0 && !deliveredNodes[index].querySelector('.reject-reason').value.trim())) return context.showToast('Mặt hàng bị từ chối phải ghi rõ lý do.', 'error');
        try { const result = await api(context, '/warehouse/receipts', { method: 'POST', body: JSON.stringify({ MaPO: data.order.MaPO, MaTBGH: data.order.MaTBGH, MaKho: overlay.querySelector('#receiptWarehouse').value, GhiChu: overlay.querySelector('#receiptNote').value, lines }) }); context.showToast(result.message, 'success'); close(); sessionStorage.setItem('fly_open_receipt', result.MaPN); context.navigate('warehouse-receipts'); await onDone(); }
        catch (error) { context.showToast(error.message, 'error'); }
      });
    } catch (error) { context.showToast(error.message, 'error'); }
  };

  const initReceiving = async (root, context) => {
    const load = async () => { try { const data = await api(context, '/warehouse/receiving/orders'); root.querySelector('#receivingBody').innerHTML = data.items.length ? data.items.map(item => { const action = item.TrangThaiGiao === 'Đang giao' ? `<button class="warehouse-primary" data-arrive="${esc(item.MaTBGH)}"><svg><use href="#i-truck"></use></svg>Ghi nhận xe đến</button>` : `<button class="warehouse-primary" data-receive="${esc(item.MaTBGH)}"><svg><use href="#i-request"></use></svg>Kiểm nhận hàng</button>`; return `<tr><td><strong>${esc(item.MaTBGH)}</strong><small>Phiếu giao ${esc(item.SoPhieuGiao)}</small></td><td><strong>${esc(item.MaPO)}</strong><small>${esc(item.TenNCC)}</small></td><td><strong>${fmtDate(item.NgayGioDuKienDen)}</strong><small>${esc(item.BienSoXe || 'Chưa có biển số')}${item.SoKien === null || item.SoKien === undefined ? '' : ` · ${item.SoKien} kiện`}</small></td><td class="num"><strong>${item.TongConThieu}</strong><small>đơn vị còn thiếu</small></td><td><span class="status-pill ${statusClass(item.TrangThaiGiao)}">${esc(item.TrangThaiGiao)}</span></td><td><div class="warehouse-row-actions receiving-actions">${action}</div></td></tr>`; }).join('') : '<tr><td colspan="6" class="warehouse-empty"><strong>Chưa có chuyến hàng nào được báo đang giao.</strong><small>Nhân viên mua hàng cần ghi nhận phiếu giao hoặc vận đơn trước khi Thủ kho tiếp nhận.</small></td></tr>'; } catch (error) { context.showToast(error.message, 'error'); } };
    root.innerHTML = `${heading('KHO HÀNG / TIẾP NHẬN', 'Nhận và kiểm tra hàng', 'Theo dõi chuyến giao, ghi nhận xe đến rồi đối chiếu hàng thực tế với Đơn mua.', '<button class="warehouse-secondary" id="openReceipts"><svg><use href="#i-request"></use></svg>Danh sách Phiếu nhập</button>')}<article class="warehouse-hero"><div class="warehouse-hero-copy"><span><svg><use href="#i-truck"></use></svg> KIỂM SOÁT HÀNG ĐẾN KHO</span><h2>Xe đến kho trước, kiểm nhận hàng sau</h2><p>Thủ kho ghi nhận thời điểm xe đến, sau đó mới kiểm số lượng, chất lượng, lô và hạn dùng. Chỉ Phiếu nhập đã xác nhận mới làm tăng tồn kho.</p></div></article><article class="warehouse-table-card"><div class="warehouse-panel-title"><div><p>CHUYẾN GIAO ĐANG THỰC HIỆN</p><h2>Hàng chờ tiếp nhận</h2></div><button class="warehouse-secondary" id="refreshReceiving"><svg><use href="#i-refresh"></use></svg>Làm mới</button></div><div class="warehouse-table-wrap"><table class="warehouse-table receiving-table"><colgroup><col style="width:17%"><col style="width:22%"><col style="width:21%"><col style="width:13%"><col style="width:12%"><col style="width:15%"></colgroup><thead><tr><th>CHUYẾN GIAO</th><th>ĐƠN MUA / NCC</th><th>DỰ KIẾN ĐẾN</th><th>CÒN CHỜ GIAO</th><th>TRẠNG THÁI</th><th>THAO TÁC</th></tr></thead><tbody id="receivingBody"></tbody></table></div></article>`;
    root.querySelector('#openReceipts').addEventListener('click', () => context.navigate('warehouse-receipts')); root.querySelector('#refreshReceiving').addEventListener('click', load); root.addEventListener('click', async event => { const arrive = event.target.closest('[data-arrive]'); if (arrive) { arrive.disabled = true; try { const result = await api(context, `/warehouse/receiving/shipments/${arrive.dataset.arrive}/arrive`, { method: 'POST' }); context.showToast(result.message, 'success'); await load(); } catch (error) { arrive.disabled = false; context.showToast(error.message, 'error'); } return; } const receive = event.target.closest('[data-receive]'); if (receive) receivingModal(context, receive.dataset.receive, load); }); await load();
  };

  const initReceipts = async (root, context) => {
    const load = async () => { try { const search = root.querySelector('#receiptSearch').value; const status = root.querySelector('#receiptStatus').value; const data = await api(context, `/warehouse/receipts?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`); root.querySelector('#receiptBody').innerHTML = data.items.length ? data.items.map(item => `<tr><td><strong>${esc(item.MaPN)}</strong><small>${fmtDate(item.NgayNhap)}</small></td><td><strong>${esc(item.MaPO)}</strong><small>${esc(item.TenNCC)}</small></td><td>${esc(item.TenKho)}</td><td class="num"><strong>${item.TongChapNhan}</strong><small>đạt / ${item.TongGiao} giao</small></td><td class="num">${item.TongTuChoi}</td><td class="num"><strong>${money(item.TongTien)}</strong></td><td><span class="status-pill ${statusClass(item.TrangThai)}">${esc(item.TrangThai)}</span></td><td><button class="warehouse-secondary" data-view-receipt="${esc(item.MaPN)}">${item.TrangThai === 'Nháp' ? 'Kiểm tra & xác nhận' : 'Chi tiết'}</button></td></tr>`).join('') : '<tr><td colspan="8" class="warehouse-empty">Chưa có Phiếu nhập phù hợp.</td></tr>'; } catch (error) { context.showToast(error.message, 'error'); } };
    root.innerHTML = `${heading('KHO HÀNG / PHIẾU NHẬP', 'Phiếu nhập kho', 'Theo dõi các lần giao hàng, phần chấp nhận và phần từ chối theo từng Đơn mua.', '<button class="warehouse-primary" id="newReceiving"><svg><use href="#i-truck"></use></svg>Nhận lô hàng mới</button>')}<article class="warehouse-table-card"><div class="warehouse-toolbar"><label class="warehouse-search"><svg><use href="#i-search"></use></svg><input id="receiptSearch" placeholder="Tìm mã Phiếu nhập, Đơn mua hoặc Nhà cung cấp..."></label><div class="warehouse-toolbar-actions"><select id="receiptStatus"><option value="">Tất cả trạng thái</option><option>Nháp</option><option>Đã xác nhận</option></select><button class="warehouse-icon-button" id="refreshReceipts"><svg><use href="#i-refresh"></use></svg></button></div></div><div class="warehouse-table-wrap"><table class="warehouse-table"><thead><tr><th>PHIẾU NHẬP</th><th>ĐƠN MUA / NCC</th><th>KHO NHẬN</th><th>CHẤP NHẬN</th><th>TỪ CHỐI</th><th>GIÁ TRỊ NHẬP</th><th>TRẠNG THÁI</th><th>THAO TÁC</th></tr></thead><tbody id="receiptBody"></tbody></table></div></article>`;
    let timer; root.querySelector('#receiptSearch').addEventListener('input', () => { clearTimeout(timer); timer = setTimeout(load, 250); }); root.querySelector('#receiptStatus').addEventListener('change', load); root.querySelector('#refreshReceipts').addEventListener('click', load); root.querySelector('#newReceiving').addEventListener('click', () => context.navigate('warehouse-receiving')); root.addEventListener('click', event => { const button = event.target.closest('[data-view-receipt]'); if (button) receiptDetail(context, button.dataset.viewReceipt, load); }); await load(); const pending = sessionStorage.getItem('fly_open_receipt'); if (pending) { sessionStorage.removeItem('fly_open_receipt'); receiptDetail(context, pending, load); }
  };

  window.FLY_ROLE_PAGES = { templates: { ...(previous?.templates || {}), ...templates }, init: async (pageName, context) => { if (pageName === 'warehouse-receiving') return initReceiving(document.querySelector('.warehouse-page'), context); if (pageName === 'warehouse-receipts') return initReceipts(document.querySelector('.warehouse-page'), context); return previous?.init?.(pageName, context); } };
})();
